#server.port=8080
#spring.servlet.multipart.max-file-size=1MB
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#\u4F7F\u7528properties\u8868\u793A\u590D\u6742\u5BF9\u8C61
#person.age=18
#person.birthday=2026/05/31 19:42:22
#person.name=zhangsan
#person.like=true
#person.child.name=lisierzi
#person.child.age=10
#person.child.birthday=2019/05/31 19:42:22
#person.child.text[0]=abc
#person.child.text[1]=efe
#person.dogs[0].name=xiaohei
#person.dogs[0].id=161616
#person.dogs[1].name=xiaolan
#person.dogs[1].id=48489454
#person.cats.c1.name=lihua
#person.cats.c1.id=5454166
#person.cats.c2.name=ksdmllfaloj
#person.cats.c2.id=16469466
